<?php
include "CheckLoginForHod.php";
$TeacherID = $_GET['TeacherID'];
include "connection.php";
$select = "select *FROM `teacherslist` where `teacherID`=?";
$stmt = $conn->prepare($select);
$stmt->bind_param('s', $TeacherID);
$stmt->execute();
$result = $stmt->get_result();
$row = $result->fetch_assoc();
//////////////////////////////////
$select1 = "SELECT DISTINCT `StudentRollNumber` FROM `studentfeedback` where `TeacherID`=?";
$stmt1 = $conn->prepare($select1);
$stmt1->bind_param('s', $TeacherID);
$stmt1->execute();
$result1 = $stmt1->get_result();
$NoOfStudents = $result1->num_rows;
?>
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    <style>
        .checked {
            color: orange;
        }
        
    </style>
</head>


<body>
    <div class="container">
        <div id="content2">
            <div class="row ">
                <div class="col-sm-12 text-center">
                    <div class="card mb-4 rounded-3 shadow-sm border-success">
                        <div class="card-header py-1 text-white  border-primary">
                            <?php
                            include "header.php";
                            ?>
                        </div>
                        <div class="card mb-4 rounded-3 shadow-sm border-primary">
                            <div class="card-header py-3 text-white bg-primary border-primary">
                                <h4 class="my-0 fw-normal">Feedback Report Of <?php echo $row['TeacherName'] . ' Department ' . $row['Branch']; ?></h4>
                            </div>
                            <a href="HodHomePage.php" class="nav-item nav-link text-left">Home</a>
                            
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div id="errorhide">
                                            <?php
                                            if (isset($_SESSION['success'])) {
                                                echo '<div class="alert alert-success ">' . $_SESSION['success'] . '</div>';
                                                unset($_SESSION['success']);
                                            }
                                            ?>
                                        </div>
                                        <div class="table-responsive">
                                            <table class="table table-bordered table-hover">
                                                <thead>
                                                    <tr class="table-info">
                                                        <th scope="col" class="text-danger" colspan="4">This is computer generated report and generated by taking average review of total <?php echo $NoOfStudents; ?> number of students</th>
                                                    </tr>
                                                    <tr class="table-info">
                                                        <th scope="col">#</th>
                                                        <th scope="col">Review Question</th>
                                                        <th scope="col">Obtained/Total</th>
                                                        <th scope="col">Average Rating</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php $i = 1;
                                                    $select2 = "SELECT *FROM `feedbackquestions`";
                                                    $stmt2 = $conn->prepare($select2);
                                                    $stmt2->execute();
                                                    $result2 = $stmt2->get_result();
                                                    $TotalQuestions = $result2->num_rows;
                                                    $TotalSum = 0;

                                                    while ($row2 = $result2->fetch_assoc()) {
                                                        $TotalFactorSum = 0;
                                                        $QuestionID = $row2['QuestionID'];
                                                        $select3 = "SELECT *FROM `studentfeedback` where `TeacherID`=? And `QuestionID`=?"; //all questions with same id
                                                        $stmt3 = $conn->prepare($select3);
                                                        $stmt3->bind_param('ss', $TeacherID, $QuestionID);
                                                        $stmt3->execute();
                                                        $result3 = $stmt3->get_result();
                                                        while ($row3 = $result3->fetch_assoc()) {
                                                            $TotalFactorSum = $TotalFactorSum + $row3['Rating'];
                                                        }
                                                        $TotalSum = $TotalSum + $TotalFactorSum;
                                                        echo '<tr>
                                                              <th scope="row">' . $i . '</th>
                                                              <td>' . $row2['Question'] . '</td>
                                                              <td>' . $TotalFactorSum . '/' . ($NoOfStudents * 5) . '</td>';
                                                        $FactorAverage = sprintf('%.2f', $TotalFactorSum / ($NoOfStudents));
                                                        echo '<td>' . $FactorAverage . '</td>
                                                            </tr>';
                                                        $i++;
                                                    }

                                                    $TotalPoints = $NoOfStudents * $TotalQuestions * 5;
                                                    $GrandTotalAverage = sprintf('%.2f', $TotalSum / ($NoOfStudents * $TotalQuestions));
                                                    echo '<tr>
                                                             
                                                              <th scope="row"colspan="2">Total Rating </th>
                                                              
                                                              <td>' . $TotalSum . '/' . $TotalPoints . '</td>
                                                              <td>' . $GrandTotalAverage . '</td>
                                                            </tr>';
                                                    ?>
                                                </tbody>
                                            </table>
                                            <div>Rating in Stars:
                                                <?PHP
                                                $whole = floor($GrandTotalAverage);     
                                                $fraction = $GrandTotalAverage - $whole;
                                                
                                                $half=0;
                                                for($i=1;$i<=$whole;$i++)
                                                {
                                                    echo'<span><img src="images/100.png" class="img-fluid" alt="Responsive image"></span>';
                                                    $half=1; 
                                                }
                                                if($fraction>0.09&&$fraction<=0.25)
                                                {
                                                     echo'<span><img src="images/25.png" class="img-fluid" alt="Responsive image"></span>';
                                                     $half=1; 
                                                }
                                                else if($fraction>0.25&&$fraction<=0.50)
                                                {
                                                     echo'<span><img src="images/50.png" class="img-fluid" alt="Responsive image"></span>';
                                                     $half=1; 
                                                }
                                                else if($fraction>0.50&&$fraction<=0.75)
                                                {
                                                     echo'<span><img src="images/75.png" class="img-fluid" alt="Responsive image"></span>';
                                                     $half=1; 
                                                }
                                                else if($fraction>0.75&&$fraction<=0.99)
                                                {
                                                     echo'<span><img src="images/100.png" class="img-fluid" alt="Responsive image"></span>';
                                                     $half=1; 
                                                }

                                                $k=$whole+$half+1;
                                                for($i=$k;$i<=5;$i++)                                 
                                                {
                                                   
                                                    echo'<span><img src="images/0.png" class="img-fluid" alt="Responsive image"></span>'; 
                                                }
                                                ?>
                                             
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-center my-2">
                                        <button class="btn btn-info" id="downloadPDF">Download in PDF</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--footer-->
    <?php
    include "footer.php";
    ?>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js"
    integrity="sha256-c9vxcXyAG4paArQG3xk6DjyW/9aHxai2ef9RpMWO44A=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#errorhide').delay(4000);
            $('#errorhide').hide(7000);
        });
    </script>
    <script>
        $('#downloadPDF').click(function() {
            domtoimage.toPng(document.getElementById('content2'))
                .then(function(blob) {
                    var pdf = new jsPDF('l', 'pt', [$('#content2').width(), $('#content2').height()]);

                    pdf.addImage(blob, 'PNG', 0, 0, $('#content2').width(), $('#content2').height());
                    pdf.save("TeacherReport.pdf");

                    that.options.api.optionsChanged();
                });
        });
        $(function() {
  function addScore(score, $domElement) {
    $("<span class='stars-container'>")
      .addClass("stars-" + score.toString())
      .text("★★★★★")
      .appendTo($domElement);
  }

  addScore(70, $("#fixture"));
});
    </script>

</body>

</html>